Repository Weiver-project/Weiver, pull requests merged in 2023-07, with the labels that each got.

#89 [Feat]: 로그인 페이지, 비밀번호 찾기 페이지
  front-end/css/login.css
  front-end/css/public.css
  front-end/html/header-footer-navi.html
  front-end/html/index.html
  front-end/html/login.html
  front-end/html/search-pw.html
  front-end/img/google_icon.png
  front-end/img/kakako-icon.png
  front-end/img/logo.png
  front-end/img/naver-icon.png
Labels: ✨feat, 🟡 Priority: Medium

#90 [Feat]: 약관 페이지
  front-end/css/login.css
  front-end/css/public.css
  front-end/html/clause.html
Labels: ✨feat, 🟡 Priority: Medium

#91 Dev
  front-end/css/login.css
  front-end/css/public.css
  front-end/css/search.css
  front-end/html/clause.html
  front-end/html/community_search.html
  front-end/html/header_footer_navi.html
  front-end/html/login.html
  front-end/html/musical_search.html
  front-end/html/search_pw.html
  front-end/img/poster.jpg
Labels: ✨feat, 🟡 Priority: Medium, 🔨refactor

#92 [Feat]: 찜했어요, 봤어요 페이지 #50
  front-end/css/search.css
  front-end/html/my_subscribe.html
Labels: ✨feat, 🟡 Priority: Medium

#94 [Design]: 커뮤니티 대댓글 페이지 #45
  front-end/css/community_comment.css
  front-end/css/login.css
  front-end/css/public.css
  front-end/css/search.css
  front-end/html/community_comment.html
Labels: 🎨design

#96 [Comment]: 띄워쓰기 및 모든 input 태그 border 제거
  front-end/css/public.css
  front-end/css/search.css
  front-end/html/community_search.html
Labels: ✏️comment

#98 [Comment]: 주석 추가
  front-end/css/community_comment.css
  front-end/css/login.css
  front-end/css/public.css
  front-end/css/search.css
  front-end/html/community_comment.html
  front-end/html/community_search.html
  front-end/html/header_footer_navi.html
  front-end/html/login.html
  front-end/html/musical_search.html
  front-end/html/my_subscribe.html
  front-end/html/search_pw.html
Labels: ✏️comment

#100 [Refacter] 프로필수정 페이지, 사진 변경 버튼 클릭 시 img파일만 받아올 수 있도록 수정 #49
  front-end/css/mypage.css
  front-end/css/profileUpdate.css
  front-end/html/profileUpdate.html
Labels: ✍️modify

#101 [Design] 커뮤니티 잡담 디테일 페이지 퍼블리싱
  front-end/css/communityDetailChat.css
  front-end/html/communityDetailChat.html
Labels: 🎨design

#139 [Refactor] 커뮤니티 페이지, 게시물 상세 페이지 (리뷰, 잡담) Public.css 적용 완료
  front-end/css/communitty.css
  front-end/css/communityDetailChat.css
  front-end/css/communityDetailReview.css
  front-end/html/communitty.html
  front-end/html/communityDetailChat.html
  front-end/html/communityDetailReview.html
Labels: 🔨refactor

#146 [Feat]: 뮤지컬 목록 API로 뮤지컬 아이디 리스트 가져오기
  back-end/data-sever/pom.xml
  back-end/data-sever/src/main/java/datasever/DataSeverApplication.java
  back-end/data-sever/src/main/java/datasever/kopis/KopisService.java
  back-end/data-sever/src/main/java/datasever/repository/MusicalRepository.java
  back-end/data-sever/src/main/java/entity/Musical.java
  back-end/data-sever/src/main/resources/application.properties
Labels: ✨feat, 🟡 Priority: Medium

#148 [Feat]: 뮤지컬 정보 저장 및 배우정보 조회 기능
  back-end/data-sever/src/main/java/datasever/DataSeverApplication.java
  back-end/data-sever/src/main/java/datasever/kopis/KopisService.java
  back-end/data-sever/src/main/java/datasever/repository/ActorRepository.java
  back-end/data-sever/src/main/java/dto/ActorDTO.java
  back-end/data-sever/src/main/java/entity/Actor.java
  back-end/data-sever/src/main/java/entity/Casting.java
  back-end/data-sever/src/main/java/entity/Musical.java
Labels: ✨feat, 🟡 Priority: Medium

#149 [comment] 스케쥴링 주기 설정 + 주석
  back-end/data-sever/src/main/java/datasever/DataSeverApplication.java
Labels: ✨feat

#166 [design] 회원가입 페이지 html, css, js(모달창)
  front-end/css/signup.css
  front-end/html/signup.html
Labels: 🎨design

#171 [Fix] 로그인 컨트롤러 예외 제거
  back-end/Weiver/src/main/java/weiver/controller/LoginController.java
  back-end/Weiver/src/main/webapp/WEB-INF/views/signup.jsp
  front-end/css/signup.css
Labels: ✍️modify

#180 [feature] 회원가입 기능 추가
  back-end/Weiver/pom.xml
  back-end/Weiver/src/main/java/weiver/config/SecurityConfig.java
  back-end/Weiver/src/main/java/weiver/controller/LoginController.java
  back-end/Weiver/src/main/java/weiver/repository/UserRepository.java
  back-end/Weiver/src/main/java/weiver/service/LoginService.java
  back-end/Weiver/src/main/resources/static/css/signup.css
  back-end/Weiver/src/main/resources/static/img/logo.png
  back-end/Weiver/src/main/webapp/WEB-INF/views/login.jsp
  back-end/Weiver/src/main/webapp/WEB-INF/views/signup.jsp
  ddl.txt
Labels: ✨feat

#209 [feature]로그인, 세션, 로그아웃, 회원 가입
  back-end/Weiver/src/main/java/weiver/config/WebConfig.java
  back-end/Weiver/src/main/java/weiver/controller/LoginController.java
  back-end/Weiver/src/main/java/weiver/controller/LoginViewController.java
  back-end/Weiver/src/main/java/weiver/entity/User.java
  back-end/Weiver/src/main/java/weiver/interceptor/SessionInterceptor.java
  back-end/Weiver/src/main/java/weiver/service/LoginService.java
  back-end/Weiver/src/main/java/weiver/service/UserService.java
  back-end/Weiver/src/main/resources/application.properties
  back-end/Weiver/src/main/webapp/WEB-INF/views/login.jsp
Labels: ✨feat

#226 [feature] 배우 기능 완료
  back-end/Weiver/src/main/java/weiver/controller/MusicalController.java
  back-end/Weiver/src/main/java/weiver/dto/ResponseCastingDTO.java
  back-end/Weiver/src/main/java/weiver/repository/CastingRepository.java
  back-end/Weiver/src/main/java/weiver/repository/MusicalRepository.java
  back-end/Weiver/src/main/java/weiver/service/ActorService.java
  back-end/Weiver/src/main/webapp/WEB-INF/views/musicalDetail.jsp
Labels: ✨feat
